[package]
name = "shared"
version = "0.1.0"
authors = ["felixLandlord <felix.landlord.nunoo@gmail.com>"]
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
